name: Security Scan with PR Comments
on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  security-events: write
  actions: read
  contents: read
  pull-requests: write  # PRへのコメント権限を追加

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::980921732235:role/CodeGuruSecurityGitHubAccessRole
          aws-region: us-east-1
          role-session-name: GitHubActionScript

      - name: CodeGuru Security
        uses: aws-actions/codeguru-security@v1
        with:
          source_path: .
          aws_region: us-east-1
          fail_on_severity: Critical

      # SARIFファイルをGitHub Security Alertsにアップロード
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: codeguru-security-results.sarif.json
          category: codeguru-security

      # 結果を解析してPRにコメント
      - name: Comment PR
        if: github.event_name == 'pull_request'
        run: |
          # SARIFファイルを解析してコメント用のテキストを生成
          FINDINGS=$(jq -r '.runs[].results[] | "- **" + .level + "**: " + .message.text + " at `" + .locations[0].physicalLocation.artifactLocation.uri + ":" + (.locations[0].physicalLocation.region.startLine | tostring) + "`"' codeguru-security-results.sarif.json)
          
          if [ -n "$FINDINGS" ]; then
            COMMENT="## CodeGuru Security Findings\n\n$FINDINGS\n\nPlease review these security issues before merging."
          
            # GitHub APIを使用してPRにコメント
            curl -X POST \
              -H "Authorization: token ${{ github.token }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
              -d "{\"body\":\"$COMMENT\"}"
          else
            echo "No security findings to report."
          fi